project:
  type: website
  output-dir: docs

website:
  title: "Ian Phillips"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false