project:
  type: website
  output-dir: docs

website:
  title: "Ian Phillips"
  search: false
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: book-reviews.qmd
        text: Reviews
      - href: cv.qmd
        text: CV
      - text: More
        menu:
          - href: online-talks.qmd
            text: Online Talks
          - href: media.qmd
            text: Media
          - href: contact.qmd
            text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    include-after-body: 
    - back-to-top.html
    - new-tab-links.html