project:
  type: website
  output-dir: docs

website:
  title: "Ian Phillips"
  search: false
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
      - text: More
        menu:
          - href: book-reviews.qmd
            text: Book Reviews
          - href: online-talks.qmd
            text: Online Talks
          - href: media.qmd
            text: Media

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false